name: 'actionlint with reviewdog'
description: 'run actionlint with reviewdog'
author: 'step-security'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
    required: true
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'actionlint'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: true
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
    required: true
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is file.
    default: 'file'
    required: true
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog. Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: |
      Deprecated, use `fail_level` instead.
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    deprecationMessage: Deprecated, use `fail_level` instead.
    default: 'false'
    required: true
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
    required: false
  actionlint_flags:
    description: 'Additional actionlint flags'
    default: ''
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/action-actionlint:v1.67.1@sha256:85548c031e9daddcab0550dccbc0616edff7ed38fbba183fc9390810b821d6ab' #v1.67.1
branding:
  color: red
  icon: check-circle
